#!/bin/csh -f

# Script to run arm_batch_repop.pro
# Peter T. Gallagher (peter.t.gallagher@gsfc.nasa.gov)
# Written: 21-feb-2001
# Modified: 2004-07-08 Russ Hewett 
# Modified: 2005-07-07 Amy Skowronek to not delete temp directory
# Adapted to run RUN_SOLMON_REPOP: 2008-18-08 Paul Higgins 
# Adapted to run as MMOTD BATCH FILE: 2013-03-07 Paul Higgins
# Run the sunspot-magnetogram overlays

	setenv OS OSX

# Record the start time
  
	setenv start_time `date -u`
	echo 'Start time: ' $start_time

# Create a temporary directory to write data to 

	setenv WORKING_PATH /Users/phiggins/science/max_millenium/idl/
	setenv TEMP_PATH /Users/phiggins/science/max_millenium/temp/
	setenv OUTPUT_PATH /Users/phiggins/science/max_millenium/images/sunspot_overlays/
	setenv todays_date `date -u +%Y%m%d`
 
echo 'set PATHS'
	
	# Set the umask for all created files, so peter,
	#	james, or russ can run arm by hand
	umask 0002

# Directories are made in SOLMON_REPOP
#	mkdir -p $TEMP_PATH
# 	mkdir -p $OUTPUT_PATH/data/$todays_date/ 

# Set SSW environment up
	setenv SSW /Applications/ssw 
#	setenv SSW /Users/solmon/ssw
	setenv SSW_INSTR "mdi eit lasco trace goes sxi hinode xrt sot eis yohkoh ontology hessi ztools ethz pfss nrl mjastereo swap aia"
	source $SSW/gen/setup/setup.ssw

echo 'sourced SSW'
  
	setenv IDL_DIR /Applications/itt/idl
	setenv IDL_PATH $WORKING_PATH

	setenv IDL_STARTUP /Users/phiggins/idl_startup.pro

	echo "@mmmotd_batch.pro" > $TEMP_PATH/mmmotd_batch.tmp

	echo 'exit' >> $TEMP_PATH/mmmotd_batch.tmp

echo 'wrote arm_batch_smart.tmp'


	$SSW/gen/setup/ssw_idl $TEMP_PATH/mmmotd_batch.tmp > $WORKING_PATH/mmmotd_batch.log

more $TEMP_PATH/mmmotd_batch.tmp

# Make a directory for todays date and copy html and png files from /tmp 

	setenv todays_date `date -u +%Y%m%d`

# Record the end time
  
	setenv end_time `date -u`
	echo 'End time: ' $end_time

# Calculate the execution time for arm_batch

	setenv start_mins `echo $start_time | cut -d: -f2` 
	setenv end_mins   `echo $end_time | cut -d: -f2` 

	setenv exec_time `expr $end_mins \- $start_mins`

	echo 'Start: ' $start_time ' End: ' $end_time >> $TEMP_PATH/mmmotd_batch_exec_times.log
	echo 'Execution time: ' $exec_time mins '\n' >> $TEMP_PATH/mmmotd_batch_exec_times.log
	
# Remove data files

#	rm -f $TEMP_PATH/*.fits