#!/bin/tcsh

#$PATH="/bin:/sbin:/usr/bin:/usr/sbin:/opt/usr/bin:/opt/usr/sbin:/usr/local/bin:/usr/local/sbin"

# Script to run arm_batch_repop.pro
# Peter T. Gallagher (peter.t.gallagher@gsfc.nasa.gov)
# Written: 21-feb-2001
# Modified: 2004-07-08 Russ Hewett 
# Modified: 2005-07-07 Amy Skowronek to not delete temp directory
# Adapted to run RUN_SOLMON_REPOP: 2008-18-08 Paul Higgins 
# Adapted to run as MMOTD BATCH FILE: 2013-03-07 Paul Higgins
# Run the sunspot-magnetogram overlays

	echo $SHELL
	ls /Users/higgins/.tcshrc

	source /Users/higgins/.tcshrc

	cd /Users/higgins/science/projects/max_millennium/idl

	setenv OS OSX

# Record the start time
  
	setenv start_time `date -u`
	echo 'Start time: ' $start_time

# Create a temporary directory to write data to 

	setenv WORKING_PATH /Users/higgins/science/projects/max_millennium/idl/
	setenv TEMP_PATH /Users/higgins/science/projects/max_millennium/temp/
	setenv OUTPUT_PATH /Users/higgins/science/projects/max_millennium/images/sharp_overlays/
	setenv todays_date `date -u +%Y%m%d`

echo 'set PATHS'
	
	# Set the umask for all created files, so peter,
	#	james, or russ can run arm by hand
	umask 0002

# Directories are made in SOLMON_REPOP
#	mkdir -p $TEMP_PATH
# 	mkdir -p $OUTPUT_PATH/data/$todays_date/ 

# Set SSW environment up
	setenv SSW /archive/ssw 
#	setenv SSW /Users/solmon/ssw
	setenv SSW_INSTR "mdi eit lasco trace goes sxi hinode xrt sot eis yohkoh ontology hessi ztools ethz pfss nrl mjastereo swap aia"
	source $SSW/gen/setup/setup.ssw

echo 'sourced SSW'
  
	setenv IDL_DIR /Applications/itt/idl704
	setenv IDL_PATH $WORKING_PATH

	setenv IDL_STARTUP /Users/higgins/science/idl_startup.pro

	echo "mmmotd_sharps_batch" > $TEMP_PATH/mmmotd_sharps_batch.tmp

	echo 'exit' >> $TEMP_PATH/mmmotd_sharps_batch.tmp

	$SSW/gen/setup/ssw_idl $TEMP_PATH/mmmotd_sharps_batch.tmp > $WORKING_PATH/mmmotd_sharps_batch.log

mv $WORKING_PATH/mmmotd_sharps_batch.log $TEMP_PATH/mmmotd_sharps_batch.log

more $TEMP_PATH/mmmotd_sharps_batch.tmp

echo 'Convert EPS files to PNGs' 
echo 'which on convert'
which convert
echo 'ls on /usr/local/bin/convert'
ls /usr/local/bin/convert


	set date=`date -u +%Y%m%d`
	set imglisteps=`ls /Users/higgins/science/projects/max_millennium/images/sharp_overlays/*$date*eps`

	echo 'List the EPS files:'
	ls /Users/higgins/science/projects/max_millennium/images/sharp_overlays/*$date*eps

	foreach i ($imglisteps)
	    echo $i
	    echo $i'.png'
	    echo '/usr/local/bin/convert -density 200 '$i' '$i'.png'

	    /usr/local/bin/convert -density 200 $i $i.png

	end

echo 'Remove files from public directory'
	echo 'Files in remote directory:'
	ls /sanhome/higgins/public_html/max_millennium/sharp_overlays/sharpoverlay_*.png

	rm -f /sanhome/higgins/public_html/max_millennium/sharp_overlays/sharpoverlay_*.png

echo 'Copy png files from local directory to public'

	echo 'ls on PNG files written for $date'
	ls /Users/higgins/science/projects/max_millennium/images/sharp_overlays/*$date*png

	set imglist=`ls /Users/higgins/science/projects/max_millennium/images/sharp_overlays/*$date*png`
	cp $imglist /sanhome/higgins/public_html/max_millennium/sharp_overlays/

# Record the end time
  
	setenv end_time `date -u`
	echo 'End time: ' $end_time

# Calculate the execution time for arm_batch

	setenv start_mins `echo $start_time | cut -d: -f2` 
	setenv end_mins   `echo $end_time | cut -d: -f2` 

	setenv exec_time `expr $end_mins \- $start_mins`

	echo 'Start: ' $start_time ' End: ' $end_time >> $TEMP_PATH/mmmotd_sharps_batch_exec_times.log
	echo 'Execution time: ' $exec_time mins '\n' >> $TEMP_PATH/mmmotd_sharps_batch_exec_times.log
	
# Remove data files

#	rm -f $TEMP_PATH/*.fits
